[rocks]
[plugins]
# --------- TREESITTER PARSERS ---------
tree-sitter-c = "scm"
tree-sitter-lua = "scm"
tree-sitter-vim = "scm"
tree-sitter-vimdoc = "scm"
tree-sitter-query = "scm"
tree-sitter-c_sharp = "scm"
tree-sitter-python = "scm"
tree-sitter-bash = "scm"
tree-sitter-go = "scm"
tree-sitter-yaml = "scm"
tree-sitter-toml = "scm"
tree-sitter-csv = "scm"
tree-sitter-dockerfile = "scm"
tree-sitter-norg-meta = "0.1.0"
tree-sitter-norg = "0.2.4"
tree-sitter-sql = "scm"
tree-sitter-html = "scm"
tree-sitter-http = "scm"
# --------- TREESITTER PARSERS ---------

"lua-utils.nvim" = "1.0.2"
"rocks-config.nvim" = "1.6.0"
"rocks-dev.nvim" = "1.2.3"
"rocks-git.nvim" = "1.5.1"
"rocks-lazy.nvim" = "scm"
"rocks.nvim" = "2.31.1"
luasnip = "2.3.0"
nvim-dap = "0.8.0"
nvim-web-devicons = "0.100"
neogit = "scm"
"rocks-treesitter.nvim" = "scm"
"gruvbox.nvim" = "2.0.0"
"conform.nvim" = "5.9.0"
nvim-lspconfig = { version = "0.1.8", opt = true }
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = { version = "1.29.0" }
"obsidian.nvim" = "3.7.9"
nvim-dap-ui = "4.0.0"
"structlog.nvim" = "0.1"
"overseer.nvim" = "1.4.0"
"neodev.nvim" = "3.0.0"
"mason-nvim-dap.nvim" = "2.3.0"
"oil.nvim" = "2.9.0"
"zen-mode.nvim" = "1.3.0"
magick = "1.6.0"
"image.nvim" = "1.3.0"
nvim-nio= "1.9.4"
"fugit2.nvim" = "0.2.0"
"mini.diff" = "0.13.0"

[plugins."telescope.nvim"]
version = "0.1.8"
opt = true
cmd = "Telescope"

[plugins.neorg]
version = "8.7.1"
opt = true
ft = "norg"

[plugins.plenary]
git = "nvim-lua/plenary.nvim"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.2^{}"

[plugins.nvim-cmp]
git = "hrsh7th/nvim-cmp"

[plugins.cmp_luasnip]
git = "saadparwaiz1/cmp_luasnip"

[plugins.cmp-nvim-lsp]
git = "hrsh7th/cmp-nvim-lsp"

[plugins.roslyn]
git = "jmederosalvarado/roslyn.nvim"

# Git
[plugins.diffview]
git = "sindrets/diffview.nvim"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.9.0"

# Testing
[plugins.nvim-neotest]
git = "nvim-neotest/neotest"
[plugins.neotest-dotnet]
git = "Issafalcon/neotest-dotnet"
[plugins.neotest-python]
git = "nvim-neotest/neotest-python"
[plugins.neotest-plenary]
git = "nvim-neotest/neotest-plenary"
[plugins.structlog]
git = "Tastyep/structlog.nvim"

[plugins.lualine]
git = "nvim-lualine/lualine.nvim"

[plugins.harpoon]
git = "ThePrimeagen/harpoon"
branch = "harpoon2"

[plugins.undotree]
git = "mbbill/undotree"

[plugins.telescope-fzf-native-nvim]
git = "nvim-telescope/telescope-fzf-native.nvim"
build = "make"

[plugins.neorg-telescope]
git = "nvim-neorg/neorg-telescope"

[plugins.mini-starter]
git = "echasnovski/mini.starter"

[plugins.nvim-dap-cs]
git = "NicholasMata/nvim-dap-cs"

[plugins.everforest-nvim]
git = "neanias/everforest-nvim"

[plugins.melange]
git = "savq/melange-nvim"

[plugins.colorizer]
git = "norcalli/nvim-colorizer.lua"

[plugins.razor-nvim]
git = "moreiraio/razor.nvim"

[plugins.img-clip-nvim]
git = "HakonHarnes/img-clip.nvim"

[plugins.trouble]
git = "folke/trouble.nvim"

[plugins.copilot-lua]
git = "zbirenbaum/copilot.lua"

[plugins.neorg-templates]
git = "pysan3/neorg-templates"

[config]
auto_setup = true
