# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"lua-utils.nvim" = "1.0.2"
"rocks-config.nvim" = "1.6.0"
"rocks-dev.nvim" = "1.2.1"
"rocks-git.nvim" = "1.5.1"
"rocks.nvim" = "2.29.0"
"telescope.nvim" = "scm"
luasnip = "2.3.0"
nvim-dap = "0.7.0"
nvim-web-devicons = "0.100"
neogit = "scm"
"rocks-treesitter.nvim" = "scm"

# --------- TREESITTER PARSERS ---------
tree-sitter-c = "scm"
tree-sitter-lua = "scm"
tree-sitter-vim = "scm"
tree-sitter-vimdoc = "scm"
tree-sitter-query = "scm"
tree-sitter-c_sharp = "scm"
"gruvbox.nvim" = "2.0.0"
"conform.nvim" = "5.8.0"
nvim-lspconfig = { version = "0.1.8", opt = true }
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = { version = "1.29.0" }
"obsidian.nvim" = "3.7.9"
nvim-dap-ui = "4.0.0"
"structlog.nvim" = "0.1"
"overseer.nvim" = "1.4.0"
"neodev.nvim" = "2.5.2"
"mason-nvim-dap.nvim" = "2.2.2"
"oil.nvim" = "2.9.0"
neorg = "8.5.0"
"zen-mode.nvim" = "1.3.0"
magick = "1.6.0"
"image.nvim" = "1.3.0"
nvim-nio= "1.9.3"
"lspsaga.nvim" = "scm"

[plugins.plenary]
git = "nvim-lua/plenary.nvim"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.2^{}"

[plugins.nvim-cmp]
git = "hrsh7th/nvim-cmp"

[plugins.cmp_luasnip]
git = "saadparwaiz1/cmp_luasnip"

[plugins.cmp-nvim-lsp]
git = "hrsh7th/cmp-nvim-lsp"

[plugins.trouble]
git = "folke/trouble.nvim"
branch = "dev"

[plugins.roslyn]
git = "jmederosalvarado/roslyn.nvim"

# Git
[plugins.diffview]
git = "sindrets/diffview.nvim"
[plugins.blame]
git = "FabijanZulj/blame.nvim"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.8.1"

# Testing
[plugins.nvim-neotest]
git = "nvim-neotest/neotest"
[plugins.neotest-dotnet]
git = "Issafalcon/neotest-dotnet"
[plugins.neotest-python]
git = "nvim-neotest/neotest-python"
[plugins.neotest-plenary]
git = "nvim-neotest/neotest-plenary"
[plugins.structlog]
git = "Tastyep/structlog.nvim"

[plugins.lualine]
git = "nvim-lualine/lualine.nvim"

[plugins.harpoon]
git = "ThePrimeagen/harpoon"
branch = "harpoon2"

[plugins.undotree]
git = "mbbill/undotree"

[plugins.telescope-fzf-native-nvim]
git = "nvim-telescope/telescope-fzf-native.nvim"
build = "make"

[plugins.neorg-telescope]
git = "nvim-neorg/neorg-telescope"

[plugins.mini-starter]
git = "echasnovski/mini.starter"

[plugins.nvim-dap-cs]
git = "NicholasMata/nvim-dap-cs"

[plugins.everforest-nvim]
git = "neanias/everforest-nvim"

[plugins.melange]
git = "savq/melange-nvim"


[plugins.colorizer]
git = "norcalli/nvim-colorizer.lua"

[plugins.razor-nvim]
git = "moreiraio/razor.nvim"

[plugins.img-clip-nvim]
git = "HakonHarnes/img-clip.nvim"

[plugins."lspsaga-nvim"]
git = "nvimdev/lspsaga.nvim"
opt = true

[config]
auto_setup = true
